### ISSUE TITLE
Different tables classes?

### ISSUE THREAD

**Issue by janstieler** [julien-gargot/kirby-plugin-table#1]
Hi,
it would be nice if its possible to add classes direct in the kirbytext.
It could be useful if you have multiple tables on one site but with different styling.

Cheers

**Comment by julien-gargot** [comment]
Hi,

Thank for your return.

From my point of view, clients should not have the possibility to change a graphic style.

But, if it’s relevant from a semantic way, maybe you could just duplicate the `(table…)` tag for others with a particular style in your CSS. For example `(numerical-data…)` and `(main-data…)`.
