### ISSUE TITLE
idea: add classes to table and td

### ISSUE THREAD

**Issue by bnomei** [julien-gargot/kirby-plugin-table#2]
just a quick hack. you can sure do better and maybe add proper support.

you can then write 

```
(table...)

{{class="my-table-style"}}
```

which will result in <table class="my-table-style">...

```
<?php
/**
 * Table Plugin
 * based on Bastian Allgeier <bastian@getkirby.com> Columns plugin.
 *
 * @author Julien Gargot <julien@g-u-i.net>
 * @version 1.1.0
 *
 * Extended with GetStringBetween and AddHtmlCodeToTag by bnomei
 */

if(!function_exists('GetStringBetween')) {
  function GetStringBetween ($string, $start, $finish, $mustBeginWith = false) {
    $string = " ".$string;
    $position = strpos($string, $start);
    if ($position === FALSE) return "";
    if($mustBeginWith && $position != 1) return "";
    $position += strlen($start);
    $length = strpos($string, $finish, $position) - $position;
    return substr($string, $position, $length);
  }
}

if(!function_exists('AddHtmlCodeToTag')) {
  function AddHtmlCodeToTag(&$column, $mustBeginWith) {
    $column = trim($column);
    $hext = GetStringBetween($column, '{{', '}}', $mustBeginWith);
    if(strlen($hext)) { 
      if($mustBeginWith) $column = preg_replace('/{{'.$hext.'}}/', '', $column, 1);  // NOTE: count = 1
      else $column = str_replace('{{'.$hext.'}}', '', $column);
    }
    return ' '.trim($hext); 
  }
}


kirbytext::$pre[] = function($kirbytext, $text) {
  $text = preg_replace_callback('!\(table(…|\.{3})\)(.*?)\((…|\.{3})table\)!is', function($matches) use($kirbytext) {
    $ma =  $matches[2];
    $tae = AddHtmlCodeToTag($ma, true); // $column by REF
    $rows = preg_split('!(\n|\r\n)(\+{4}|\((…|\.{3})row(…|\.{3})\))\s+(\n|\r\n)!', $ma);
    $html = array();
    foreach($rows as $row) {
      $tre = AddHtmlCodeToTag($row, true); // $column by REF
      $field       = new Field($kirbytext->field->page, null, trim($row));
      $columns     = preg_split('!(\n|\r\n)(\/{4}|\((…|\.{3})column(…|\.{3})\))\s+(\n|\r\n)!', $field);
      $htmlColumns = array();
      foreach($columns as $column) {
        $tde = AddHtmlCodeToTag($column); // $column by REF
        $field = new Field($kirbytext->field->page, null, trim($column));
        $htmlColumns[] = '<td'.$tde.'>' . kirbytext($field) . '</td>';
      }
      $html[] = '<tr'.$tre.'>' . implode($htmlColumns) . '</tr>';
    }
    //return '<table class="' . c::get('table.container', 'table') . '">' . implode($html) . '</table>';
    if(strlen(trim($tae)) == 0) {
      $tae = ' class="' . c::get('table.container', 'table') . '"';
    }
    return '<table'.$tae.'>' . implode($html) . '</table>';
  }, $text);
  return $text;
};
```

**Comment by julien-gargot** [comment]
Hi, thank you for the hint, but as I said on issue #1, for me clients should not be able to change graphic design. ;)

**Comment by bnomei** [comment]
right. they should not. my code above is obviously a hack. 
but if i have two awesome styled tables how can the client choose? like for blogpages with different table styles. 
i did not suggest you add an snippet injecting code like i did. just adding support for an additional class tag would not hurt imho. i missed it very much, since most kirbytags (image, file,...) support adding custom classes.

**Comment by julien-gargot** [comment]
> but if i have two awesome styled tables how can the client choose? like for blogpages with different table styles. 

Like I said in comment on #1, just duplicate the table plugin and create new tags. It will be super easy for you, or your users, to differentiate the type of data.

> i missed it very much, since most kirbytags (image, file,...) support adding custom classes.

But yes, I know, that it should be done.
An opening tag like `(table… class: a-class-name)` ?

:smile:

**Comment by bnomei** [comment]
yes, i did read that. i am not looking for a solution but an improvement. but i get you do not want to add this kind of functionality. no problem.

```
(table...awsome)
text
(...column...massiv)
text
(...table)
```

**Comment by julien-gargot** [comment]
Yes, on the column too. But it will require to set the class automatically for the same column in other rows.
`(…column… class: a-class-name)` ?

And for the ASCII system, maybe it could be :
class: a-class-name}}` ?

What if different class are set in the same column in different row?

**Comment by julien-gargot** [comment]
But anyway, this plugin should have a GUI in the panel, that may output YAML. It will be more standard… And it will be easier to add options.

**Comment by bnomei** [comment]
you are make fun of me. but thats ok.

> Il semble que la perfection soit atteinte non quand il n'y a plus rien à ajouter, mais quand il n'y a plus rien à retrancher.

**Comment by julien-gargot** [comment]
> you are make fun of me. but thats ok.

I don’t feel like I make fun of you, but maybe my bad English makes you this impression…

**Comment by bnomei** [comment]
i see. nor harm done. i will keep in touch if i have something more useful and stable to add to your repo or as a fork.
