### ISSUE TITLE
Possibility to wrap <table>

### ISSUE THREAD

**Issue by danielkoch** [julien-gargot/kirby-plugin-table#3]
It would be nice if there would be an option to wrap the `<table>` (optionally).
Example use-case: You want to insert a `<table>` based on the responsive table from [(BS component)](https://getbootstrap.com/css/#tables-responsive)

**Comment by julien-gargot** [comment]
Hi, yes that could be a good thing!

**Comment by julien-gargot** [comment]
Closed with merging your pull request. Thanks for your work. :+1:
